// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: character.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MM26.IO.Models {

  /// <summary>Holder for reflection information generated from character.proto</summary>
  public static partial class CharacterReflection {

    #region Descriptor
    /// <summary>File descriptor for character.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CharacterReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9jaGFyYWN0ZXIucHJvdG8SCWNoYXJhY3RlchoKaXRlbS5wcm90byKSAQoF",
            "RW5lbXkSFQoNY3VycmVudEhlYWx0aBgBIAEoARISCgpleHBlcmllbmNlGAIg",
            "ASgFEiUKCHBvc2l0aW9uGAMgASgLMhMuY2hhcmFjdGVyLlBvc2l0aW9uEhwK",
            "BndlYXBvbhgEIAEoCzIMLml0ZW0uV2VhcG9uEhkKBWRyb3BzGAUgAygLMgou",
            "aXRlbS5JdGVtIqsCCgZQbGF5ZXISDAoEbmFtZRgBIAEoCRIWCgNoYXQYAiAB",
            "KAsyCS5pdGVtLkhhdBIeCgdjbG90aGVzGAMgASgLMg0uaXRlbS5DbG90aGVz",
            "EhoKBXNob2VzGAQgASgLMgsuaXRlbS5TaG9lcxIcCgZ3ZWFwb24YBSABKAsy",
            "DC5pdGVtLldlYXBvbhIdCglpbnZlbnRvcnkYBiADKAsyCi5pdGVtLkl0ZW0S",
            "FQoNY3VycmVudEhlYWx0aBgHIAEoARISCgpleHBlcmllbmNlGAggASgFEiUK",
            "CHBvc2l0aW9uGAkgASgLMhMuY2hhcmFjdGVyLlBvc2l0aW9uEjAKDmFjdGl2",
            "ZV9lZmZlY3RzGAogAygLMhguaXRlbS5UZW1wU3RhdHVzTW9kaWZpZXIiMQoI",
            "UG9zaXRpb24SDwoHYm9hcmRJZBgBIAEoCRIJCgF4GAIgASgFEgkKAXkYAyAB",
            "KAVCRQohbWVjaC5tYW5pYS5lbmdpbmUuZ2FtZS5jaGFyYWN0ZXJzQg9DaGFy",
            "YWN0ZXJQcm90b3OqAg5NTTI2LklPLk1vZGVsc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MM26.IO.Models.ItemReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MM26.IO.Models.Enemy), global::MM26.IO.Models.Enemy.Parser, new[]{ "CurrentHealth", "Experience", "Position", "Weapon", "Drops" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MM26.IO.Models.Player), global::MM26.IO.Models.Player.Parser, new[]{ "Name", "Hat", "Clothes", "Shoes", "Weapon", "Inventory", "CurrentHealth", "Experience", "Position", "ActiveEffects" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MM26.IO.Models.Position), global::MM26.IO.Models.Position.Parser, new[]{ "BoardId", "X", "Y" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Enemy : pb::IMessage<Enemy> {
    private static readonly pb::MessageParser<Enemy> _parser = new pb::MessageParser<Enemy>(() => new Enemy());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Enemy> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MM26.IO.Models.CharacterReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Enemy() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Enemy(Enemy other) : this() {
      currentHealth_ = other.currentHealth_;
      experience_ = other.experience_;
      position_ = other.position_ != null ? other.position_.Clone() : null;
      weapon_ = other.weapon_ != null ? other.weapon_.Clone() : null;
      drops_ = other.drops_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Enemy Clone() {
      return new Enemy(this);
    }

    /// <summary>Field number for the "currentHealth" field.</summary>
    public const int CurrentHealthFieldNumber = 1;
    private double currentHealth_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double CurrentHealth {
      get { return currentHealth_; }
      set {
        currentHealth_ = value;
      }
    }

    /// <summary>Field number for the "experience" field.</summary>
    public const int ExperienceFieldNumber = 2;
    private int experience_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Experience {
      get { return experience_; }
      set {
        experience_ = value;
      }
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 3;
    private global::MM26.IO.Models.Position position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MM26.IO.Models.Position Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    /// <summary>Field number for the "weapon" field.</summary>
    public const int WeaponFieldNumber = 4;
    private global::MM26.IO.Models.Weapon weapon_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MM26.IO.Models.Weapon Weapon {
      get { return weapon_; }
      set {
        weapon_ = value;
      }
    }

    /// <summary>Field number for the "drops" field.</summary>
    public const int DropsFieldNumber = 5;
    private static readonly pb::FieldCodec<global::MM26.IO.Models.Item> _repeated_drops_codec
        = pb::FieldCodec.ForMessage(42, global::MM26.IO.Models.Item.Parser);
    private readonly pbc::RepeatedField<global::MM26.IO.Models.Item> drops_ = new pbc::RepeatedField<global::MM26.IO.Models.Item>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::MM26.IO.Models.Item> Drops {
      get { return drops_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Enemy);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Enemy other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(CurrentHealth, other.CurrentHealth)) return false;
      if (Experience != other.Experience) return false;
      if (!object.Equals(Position, other.Position)) return false;
      if (!object.Equals(Weapon, other.Weapon)) return false;
      if(!drops_.Equals(other.drops_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (CurrentHealth != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(CurrentHealth);
      if (Experience != 0) hash ^= Experience.GetHashCode();
      if (position_ != null) hash ^= Position.GetHashCode();
      if (weapon_ != null) hash ^= Weapon.GetHashCode();
      hash ^= drops_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (CurrentHealth != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(CurrentHealth);
      }
      if (Experience != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Experience);
      }
      if (position_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Position);
      }
      if (weapon_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Weapon);
      }
      drops_.WriteTo(output, _repeated_drops_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (CurrentHealth != 0D) {
        size += 1 + 8;
      }
      if (Experience != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Experience);
      }
      if (position_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      if (weapon_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Weapon);
      }
      size += drops_.CalculateSize(_repeated_drops_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Enemy other) {
      if (other == null) {
        return;
      }
      if (other.CurrentHealth != 0D) {
        CurrentHealth = other.CurrentHealth;
      }
      if (other.Experience != 0) {
        Experience = other.Experience;
      }
      if (other.position_ != null) {
        if (position_ == null) {
          Position = new global::MM26.IO.Models.Position();
        }
        Position.MergeFrom(other.Position);
      }
      if (other.weapon_ != null) {
        if (weapon_ == null) {
          Weapon = new global::MM26.IO.Models.Weapon();
        }
        Weapon.MergeFrom(other.Weapon);
      }
      drops_.Add(other.drops_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            CurrentHealth = input.ReadDouble();
            break;
          }
          case 16: {
            Experience = input.ReadInt32();
            break;
          }
          case 26: {
            if (position_ == null) {
              Position = new global::MM26.IO.Models.Position();
            }
            input.ReadMessage(Position);
            break;
          }
          case 34: {
            if (weapon_ == null) {
              Weapon = new global::MM26.IO.Models.Weapon();
            }
            input.ReadMessage(Weapon);
            break;
          }
          case 42: {
            drops_.AddEntriesFrom(input, _repeated_drops_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Player : pb::IMessage<Player> {
    private static readonly pb::MessageParser<Player> _parser = new pb::MessageParser<Player>(() => new Player());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Player> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MM26.IO.Models.CharacterReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Player() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Player(Player other) : this() {
      name_ = other.name_;
      hat_ = other.hat_ != null ? other.hat_.Clone() : null;
      clothes_ = other.clothes_ != null ? other.clothes_.Clone() : null;
      shoes_ = other.shoes_ != null ? other.shoes_.Clone() : null;
      weapon_ = other.weapon_ != null ? other.weapon_.Clone() : null;
      inventory_ = other.inventory_.Clone();
      currentHealth_ = other.currentHealth_;
      experience_ = other.experience_;
      position_ = other.position_ != null ? other.position_.Clone() : null;
      activeEffects_ = other.activeEffects_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Player Clone() {
      return new Player(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "hat" field.</summary>
    public const int HatFieldNumber = 2;
    private global::MM26.IO.Models.Hat hat_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MM26.IO.Models.Hat Hat {
      get { return hat_; }
      set {
        hat_ = value;
      }
    }

    /// <summary>Field number for the "clothes" field.</summary>
    public const int ClothesFieldNumber = 3;
    private global::MM26.IO.Models.Clothes clothes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MM26.IO.Models.Clothes Clothes {
      get { return clothes_; }
      set {
        clothes_ = value;
      }
    }

    /// <summary>Field number for the "shoes" field.</summary>
    public const int ShoesFieldNumber = 4;
    private global::MM26.IO.Models.Shoes shoes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MM26.IO.Models.Shoes Shoes {
      get { return shoes_; }
      set {
        shoes_ = value;
      }
    }

    /// <summary>Field number for the "weapon" field.</summary>
    public const int WeaponFieldNumber = 5;
    private global::MM26.IO.Models.Weapon weapon_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MM26.IO.Models.Weapon Weapon {
      get { return weapon_; }
      set {
        weapon_ = value;
      }
    }

    /// <summary>Field number for the "inventory" field.</summary>
    public const int InventoryFieldNumber = 6;
    private static readonly pb::FieldCodec<global::MM26.IO.Models.Item> _repeated_inventory_codec
        = pb::FieldCodec.ForMessage(50, global::MM26.IO.Models.Item.Parser);
    private readonly pbc::RepeatedField<global::MM26.IO.Models.Item> inventory_ = new pbc::RepeatedField<global::MM26.IO.Models.Item>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::MM26.IO.Models.Item> Inventory {
      get { return inventory_; }
    }

    /// <summary>Field number for the "currentHealth" field.</summary>
    public const int CurrentHealthFieldNumber = 7;
    private double currentHealth_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double CurrentHealth {
      get { return currentHealth_; }
      set {
        currentHealth_ = value;
      }
    }

    /// <summary>Field number for the "experience" field.</summary>
    public const int ExperienceFieldNumber = 8;
    private int experience_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Experience {
      get { return experience_; }
      set {
        experience_ = value;
      }
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 9;
    private global::MM26.IO.Models.Position position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MM26.IO.Models.Position Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    /// <summary>Field number for the "active_effects" field.</summary>
    public const int ActiveEffectsFieldNumber = 10;
    private static readonly pb::FieldCodec<global::MM26.IO.Models.TempStatusModifier> _repeated_activeEffects_codec
        = pb::FieldCodec.ForMessage(82, global::MM26.IO.Models.TempStatusModifier.Parser);
    private readonly pbc::RepeatedField<global::MM26.IO.Models.TempStatusModifier> activeEffects_ = new pbc::RepeatedField<global::MM26.IO.Models.TempStatusModifier>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::MM26.IO.Models.TempStatusModifier> ActiveEffects {
      get { return activeEffects_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Player);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Player other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (!object.Equals(Hat, other.Hat)) return false;
      if (!object.Equals(Clothes, other.Clothes)) return false;
      if (!object.Equals(Shoes, other.Shoes)) return false;
      if (!object.Equals(Weapon, other.Weapon)) return false;
      if(!inventory_.Equals(other.inventory_)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(CurrentHealth, other.CurrentHealth)) return false;
      if (Experience != other.Experience) return false;
      if (!object.Equals(Position, other.Position)) return false;
      if(!activeEffects_.Equals(other.activeEffects_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (hat_ != null) hash ^= Hat.GetHashCode();
      if (clothes_ != null) hash ^= Clothes.GetHashCode();
      if (shoes_ != null) hash ^= Shoes.GetHashCode();
      if (weapon_ != null) hash ^= Weapon.GetHashCode();
      hash ^= inventory_.GetHashCode();
      if (CurrentHealth != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(CurrentHealth);
      if (Experience != 0) hash ^= Experience.GetHashCode();
      if (position_ != null) hash ^= Position.GetHashCode();
      hash ^= activeEffects_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (hat_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Hat);
      }
      if (clothes_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Clothes);
      }
      if (shoes_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Shoes);
      }
      if (weapon_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Weapon);
      }
      inventory_.WriteTo(output, _repeated_inventory_codec);
      if (CurrentHealth != 0D) {
        output.WriteRawTag(57);
        output.WriteDouble(CurrentHealth);
      }
      if (Experience != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Experience);
      }
      if (position_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(Position);
      }
      activeEffects_.WriteTo(output, _repeated_activeEffects_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (hat_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Hat);
      }
      if (clothes_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Clothes);
      }
      if (shoes_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Shoes);
      }
      if (weapon_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Weapon);
      }
      size += inventory_.CalculateSize(_repeated_inventory_codec);
      if (CurrentHealth != 0D) {
        size += 1 + 8;
      }
      if (Experience != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Experience);
      }
      if (position_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      size += activeEffects_.CalculateSize(_repeated_activeEffects_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Player other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.hat_ != null) {
        if (hat_ == null) {
          Hat = new global::MM26.IO.Models.Hat();
        }
        Hat.MergeFrom(other.Hat);
      }
      if (other.clothes_ != null) {
        if (clothes_ == null) {
          Clothes = new global::MM26.IO.Models.Clothes();
        }
        Clothes.MergeFrom(other.Clothes);
      }
      if (other.shoes_ != null) {
        if (shoes_ == null) {
          Shoes = new global::MM26.IO.Models.Shoes();
        }
        Shoes.MergeFrom(other.Shoes);
      }
      if (other.weapon_ != null) {
        if (weapon_ == null) {
          Weapon = new global::MM26.IO.Models.Weapon();
        }
        Weapon.MergeFrom(other.Weapon);
      }
      inventory_.Add(other.inventory_);
      if (other.CurrentHealth != 0D) {
        CurrentHealth = other.CurrentHealth;
      }
      if (other.Experience != 0) {
        Experience = other.Experience;
      }
      if (other.position_ != null) {
        if (position_ == null) {
          Position = new global::MM26.IO.Models.Position();
        }
        Position.MergeFrom(other.Position);
      }
      activeEffects_.Add(other.activeEffects_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            if (hat_ == null) {
              Hat = new global::MM26.IO.Models.Hat();
            }
            input.ReadMessage(Hat);
            break;
          }
          case 26: {
            if (clothes_ == null) {
              Clothes = new global::MM26.IO.Models.Clothes();
            }
            input.ReadMessage(Clothes);
            break;
          }
          case 34: {
            if (shoes_ == null) {
              Shoes = new global::MM26.IO.Models.Shoes();
            }
            input.ReadMessage(Shoes);
            break;
          }
          case 42: {
            if (weapon_ == null) {
              Weapon = new global::MM26.IO.Models.Weapon();
            }
            input.ReadMessage(Weapon);
            break;
          }
          case 50: {
            inventory_.AddEntriesFrom(input, _repeated_inventory_codec);
            break;
          }
          case 57: {
            CurrentHealth = input.ReadDouble();
            break;
          }
          case 64: {
            Experience = input.ReadInt32();
            break;
          }
          case 74: {
            if (position_ == null) {
              Position = new global::MM26.IO.Models.Position();
            }
            input.ReadMessage(Position);
            break;
          }
          case 82: {
            activeEffects_.AddEntriesFrom(input, _repeated_activeEffects_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Position : pb::IMessage<Position> {
    private static readonly pb::MessageParser<Position> _parser = new pb::MessageParser<Position>(() => new Position());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Position> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MM26.IO.Models.CharacterReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Position() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Position(Position other) : this() {
      boardId_ = other.boardId_;
      x_ = other.x_;
      y_ = other.y_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Position Clone() {
      return new Position(this);
    }

    /// <summary>Field number for the "boardId" field.</summary>
    public const int BoardIdFieldNumber = 1;
    private string boardId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string BoardId {
      get { return boardId_; }
      set {
        boardId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 2;
    private int x_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int X {
      get { return x_; }
      set {
        x_ = value;
      }
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 3;
    private int y_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Y {
      get { return y_; }
      set {
        y_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Position);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Position other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BoardId != other.BoardId) return false;
      if (X != other.X) return false;
      if (Y != other.Y) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (BoardId.Length != 0) hash ^= BoardId.GetHashCode();
      if (X != 0) hash ^= X.GetHashCode();
      if (Y != 0) hash ^= Y.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (BoardId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(BoardId);
      }
      if (X != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(X);
      }
      if (Y != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Y);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (BoardId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BoardId);
      }
      if (X != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(X);
      }
      if (Y != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Y);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Position other) {
      if (other == null) {
        return;
      }
      if (other.BoardId.Length != 0) {
        BoardId = other.BoardId;
      }
      if (other.X != 0) {
        X = other.X;
      }
      if (other.Y != 0) {
        Y = other.Y;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            BoardId = input.ReadString();
            break;
          }
          case 16: {
            X = input.ReadInt32();
            break;
          }
          case 24: {
            Y = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
