// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: game_state.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MM26.IO.Models {

  /// <summary>Holder for reflection information generated from game_state.proto</summary>
  public static partial class GameStateReflection {

    #region Descriptor
    /// <summary>File descriptor for game_state.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameStateReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBnYW1lX3N0YXRlLnByb3RvEgpnYW1lX3N0YXRlGgtib2FyZC5wcm90bxoP",
            "Y2hhcmFjdGVyLnByb3RvIqgDCglHYW1lU3RhdGUSEAoIc3RhdGVfaWQYASAB",
            "KAMSOgoLYm9hcmRfbmFtZXMYAiADKAsyJS5nYW1lX3N0YXRlLkdhbWVTdGF0",
            "ZS5Cb2FyZE5hbWVzRW50cnkSPAoMcGxheWVyX25hbWVzGAMgAygLMiYuZ2Ft",
            "ZV9zdGF0ZS5HYW1lU3RhdGUuUGxheWVyTmFtZXNFbnRyeRI+Cg1tb25zdGVy",
            "X25hbWVzGAQgAygLMicuZ2FtZV9zdGF0ZS5HYW1lU3RhdGUuTW9uc3Rlck5h",
            "bWVzRW50cnkaPwoPQm9hcmROYW1lc0VudHJ5EgsKA2tleRgBIAEoCRIbCgV2",
            "YWx1ZRgCIAEoCzIMLmJvYXJkLkJvYXJkOgI4ARpFChBQbGF5ZXJOYW1lc0Vu",
            "dHJ5EgsKA2tleRgBIAEoCRIgCgV2YWx1ZRgCIAEoCzIRLmNoYXJhY3Rlci5Q",
            "bGF5ZXI6AjgBGkcKEU1vbnN0ZXJOYW1lc0VudHJ5EgsKA2tleRgBIAEoCRIh",
            "CgV2YWx1ZRgCIAEoCzISLmNoYXJhY3Rlci5Nb25zdGVyOgI4ASIfCgpHYW1l",
            "Q2hhbmdlEhEKCWNoYW5nZV9pZBgBIAEoA0JAChxtZWNoLm1hbmlhLmVuZ2lu",
            "ZS5nYW1lLm1vZGVsQg9HYW1lU3RhdGVQcm90b3OqAg5NTTI2LklPLk1vZGVs",
            "c2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MM26.IO.Models.BoardReflection.Descriptor, global::MM26.IO.Models.CharacterReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MM26.IO.Models.GameState), global::MM26.IO.Models.GameState.Parser, new[]{ "StateId", "BoardNames", "PlayerNames", "MonsterNames" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::MM26.IO.Models.GameChange), global::MM26.IO.Models.GameChange.Parser, new[]{ "ChangeId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GameState : pb::IMessage<GameState>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GameState> _parser = new pb::MessageParser<GameState>(() => new GameState());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GameState> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MM26.IO.Models.GameStateReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameState() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameState(GameState other) : this() {
      stateId_ = other.stateId_;
      boardNames_ = other.boardNames_.Clone();
      playerNames_ = other.playerNames_.Clone();
      monsterNames_ = other.monsterNames_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameState Clone() {
      return new GameState(this);
    }

    /// <summary>Field number for the "state_id" field.</summary>
    public const int StateIdFieldNumber = 1;
    private long stateId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long StateId {
      get { return stateId_; }
      set {
        stateId_ = value;
      }
    }

    /// <summary>Field number for the "board_names" field.</summary>
    public const int BoardNamesFieldNumber = 2;
    private static readonly pbc::MapField<string, global::MM26.IO.Models.Board>.Codec _map_boardNames_codec
        = new pbc::MapField<string, global::MM26.IO.Models.Board>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::MM26.IO.Models.Board.Parser), 18);
    private readonly pbc::MapField<string, global::MM26.IO.Models.Board> boardNames_ = new pbc::MapField<string, global::MM26.IO.Models.Board>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::MM26.IO.Models.Board> BoardNames {
      get { return boardNames_; }
    }

    /// <summary>Field number for the "player_names" field.</summary>
    public const int PlayerNamesFieldNumber = 3;
    private static readonly pbc::MapField<string, global::MM26.IO.Models.Player>.Codec _map_playerNames_codec
        = new pbc::MapField<string, global::MM26.IO.Models.Player>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::MM26.IO.Models.Player.Parser), 26);
    private readonly pbc::MapField<string, global::MM26.IO.Models.Player> playerNames_ = new pbc::MapField<string, global::MM26.IO.Models.Player>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::MM26.IO.Models.Player> PlayerNames {
      get { return playerNames_; }
    }

    /// <summary>Field number for the "monster_names" field.</summary>
    public const int MonsterNamesFieldNumber = 4;
    private static readonly pbc::MapField<string, global::MM26.IO.Models.Monster>.Codec _map_monsterNames_codec
        = new pbc::MapField<string, global::MM26.IO.Models.Monster>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::MM26.IO.Models.Monster.Parser), 34);
    private readonly pbc::MapField<string, global::MM26.IO.Models.Monster> monsterNames_ = new pbc::MapField<string, global::MM26.IO.Models.Monster>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::MM26.IO.Models.Monster> MonsterNames {
      get { return monsterNames_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GameState);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GameState other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StateId != other.StateId) return false;
      if (!BoardNames.Equals(other.BoardNames)) return false;
      if (!PlayerNames.Equals(other.PlayerNames)) return false;
      if (!MonsterNames.Equals(other.MonsterNames)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StateId != 0L) hash ^= StateId.GetHashCode();
      hash ^= BoardNames.GetHashCode();
      hash ^= PlayerNames.GetHashCode();
      hash ^= MonsterNames.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (StateId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(StateId);
      }
      boardNames_.WriteTo(output, _map_boardNames_codec);
      playerNames_.WriteTo(output, _map_playerNames_codec);
      monsterNames_.WriteTo(output, _map_monsterNames_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StateId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(StateId);
      }
      size += boardNames_.CalculateSize(_map_boardNames_codec);
      size += playerNames_.CalculateSize(_map_playerNames_codec);
      size += monsterNames_.CalculateSize(_map_monsterNames_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GameState other) {
      if (other == null) {
        return;
      }
      if (other.StateId != 0L) {
        StateId = other.StateId;
      }
      boardNames_.Add(other.boardNames_);
      playerNames_.Add(other.playerNames_);
      monsterNames_.Add(other.monsterNames_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StateId = input.ReadInt64();
            break;
          }
          case 18: {
            boardNames_.AddEntriesFrom(input, _map_boardNames_codec);
            break;
          }
          case 26: {
            playerNames_.AddEntriesFrom(input, _map_playerNames_codec);
            break;
          }
          case 34: {
            monsterNames_.AddEntriesFrom(input, _map_monsterNames_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            StateId = input.ReadInt64();
            break;
          }
          case 18: {
            boardNames_.AddEntriesFrom(ref input, _map_boardNames_codec);
            break;
          }
          case 26: {
            playerNames_.AddEntriesFrom(ref input, _map_playerNames_codec);
            break;
          }
          case 34: {
            monsterNames_.AddEntriesFrom(ref input, _map_monsterNames_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class GameChange : pb::IMessage<GameChange>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GameChange> _parser = new pb::MessageParser<GameChange>(() => new GameChange());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GameChange> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MM26.IO.Models.GameStateReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameChange() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameChange(GameChange other) : this() {
      changeId_ = other.changeId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameChange Clone() {
      return new GameChange(this);
    }

    /// <summary>Field number for the "change_id" field.</summary>
    public const int ChangeIdFieldNumber = 1;
    private long changeId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long ChangeId {
      get { return changeId_; }
      set {
        changeId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GameChange);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GameChange other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ChangeId != other.ChangeId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ChangeId != 0L) hash ^= ChangeId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ChangeId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(ChangeId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ChangeId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ChangeId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GameChange other) {
      if (other == null) {
        return;
      }
      if (other.ChangeId != 0L) {
        ChangeId = other.ChangeId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ChangeId = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ChangeId = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
