// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: player_protos.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MM26.IO.Models {

  /// <summary>Holder for reflection information generated from player_protos.proto</summary>
  public static partial class PlayerProtosReflection {

    #region Descriptor
    /// <summary>File descriptor for player_protos.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlayerProtosReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNwbGF5ZXJfcHJvdG9zLnByb3RvEhRwbGF5ZXJfY29tbXVuaWNhdGlvbhoQ",
            "Z2FtZV9zdGF0ZS5wcm90bxoPY2hhcmFjdGVyLnByb3RvIvIBCg5QbGF5ZXJE",
            "ZWNpc2lvbhJHCgxkZWNpc2lvblR5cGUYASABKA4yMS5wbGF5ZXJfY29tbXVu",
            "aWNhdGlvbi5QbGF5ZXJEZWNpc2lvbi5EZWNpc2lvblR5cGUSKwoOdGFyZ2V0",
            "UG9zaXRpb24YAiABKAsyEy5jaGFyYWN0ZXIuUG9zaXRpb24SDQoFaW5kZXgY",
            "AyABKAUiWwoMRGVjaXNpb25UeXBlEggKBE5PTkUQABIICgRNT1ZFEAESCgoG",
            "QVRUQUNLEAISCgoGUE9SVEFMEAMSCAoERFJPUBAEEgkKBUVRVUlQEAUSCgoG",
            "UElDS1VQEAYiYQoKUGxheWVyVHVybhIpCgpnYW1lX3N0YXRlGAEgASgLMhUu",
            "Z2FtZV9zdGF0ZS5HYW1lU3RhdGUSDwoFdGVzdDEYAiABKAlIABIPCgV0ZXN0",
            "MhgDIAEoBUgAQgYKBHRlc3RCVAozbWVjaC5tYW5pYS5lbmdpbmUuc2VydmVy",
            "LmNvbW11bmljYXRpb24ucGxheWVyLm1vZGVsQgxQbGF5ZXJQcm90b3OqAg5N",
            "TTI2LklPLk1vZGVsc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MM26.IO.Models.GameStateReflection.Descriptor, global::MM26.IO.Models.CharacterReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MM26.IO.Models.PlayerDecision), global::MM26.IO.Models.PlayerDecision.Parser, new[]{ "DecisionType", "TargetPosition", "Index" }, null, new[]{ typeof(global::MM26.IO.Models.PlayerDecision.Types.DecisionType) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::MM26.IO.Models.PlayerTurn), global::MM26.IO.Models.PlayerTurn.Parser, new[]{ "GameState", "Test1", "Test2" }, new[]{ "Test" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Proto sent from player to engine
  /// </summary>
  public sealed partial class PlayerDecision : pb::IMessage<PlayerDecision>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerDecision> _parser = new pb::MessageParser<PlayerDecision>(() => new PlayerDecision());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PlayerDecision> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MM26.IO.Models.PlayerProtosReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerDecision() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerDecision(PlayerDecision other) : this() {
      decisionType_ = other.decisionType_;
      targetPosition_ = other.targetPosition_ != null ? other.targetPosition_.Clone() : null;
      index_ = other.index_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerDecision Clone() {
      return new PlayerDecision(this);
    }

    /// <summary>Field number for the "decisionType" field.</summary>
    public const int DecisionTypeFieldNumber = 1;
    private global::MM26.IO.Models.PlayerDecision.Types.DecisionType decisionType_ = global::MM26.IO.Models.PlayerDecision.Types.DecisionType.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MM26.IO.Models.PlayerDecision.Types.DecisionType DecisionType {
      get { return decisionType_; }
      set {
        decisionType_ = value;
      }
    }

    /// <summary>Field number for the "targetPosition" field.</summary>
    public const int TargetPositionFieldNumber = 2;
    private global::MM26.IO.Models.Position targetPosition_;
    /// <summary>
    /// For MOVE, ATTACK
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MM26.IO.Models.Position TargetPosition {
      get { return targetPosition_; }
      set {
        targetPosition_ = value;
      }
    }

    /// <summary>Field number for the "index" field.</summary>
    public const int IndexFieldNumber = 3;
    private int index_;
    /// <summary>
    /// For TRAVEL, DROP, EQUIP, PICKUP
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Index {
      get { return index_; }
      set {
        index_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PlayerDecision);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PlayerDecision other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DecisionType != other.DecisionType) return false;
      if (!object.Equals(TargetPosition, other.TargetPosition)) return false;
      if (Index != other.Index) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (DecisionType != global::MM26.IO.Models.PlayerDecision.Types.DecisionType.None) hash ^= DecisionType.GetHashCode();
      if (targetPosition_ != null) hash ^= TargetPosition.GetHashCode();
      if (Index != 0) hash ^= Index.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (DecisionType != global::MM26.IO.Models.PlayerDecision.Types.DecisionType.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) DecisionType);
      }
      if (targetPosition_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TargetPosition);
      }
      if (Index != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Index);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (DecisionType != global::MM26.IO.Models.PlayerDecision.Types.DecisionType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) DecisionType);
      }
      if (targetPosition_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TargetPosition);
      }
      if (Index != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Index);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PlayerDecision other) {
      if (other == null) {
        return;
      }
      if (other.DecisionType != global::MM26.IO.Models.PlayerDecision.Types.DecisionType.None) {
        DecisionType = other.DecisionType;
      }
      if (other.targetPosition_ != null) {
        if (targetPosition_ == null) {
          TargetPosition = new global::MM26.IO.Models.Position();
        }
        TargetPosition.MergeFrom(other.TargetPosition);
      }
      if (other.Index != 0) {
        Index = other.Index;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            DecisionType = (global::MM26.IO.Models.PlayerDecision.Types.DecisionType) input.ReadEnum();
            break;
          }
          case 18: {
            if (targetPosition_ == null) {
              TargetPosition = new global::MM26.IO.Models.Position();
            }
            input.ReadMessage(TargetPosition);
            break;
          }
          case 24: {
            Index = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            DecisionType = (global::MM26.IO.Models.PlayerDecision.Types.DecisionType) input.ReadEnum();
            break;
          }
          case 18: {
            if (targetPosition_ == null) {
              TargetPosition = new global::MM26.IO.Models.Position();
            }
            input.ReadMessage(TargetPosition);
            break;
          }
          case 24: {
            Index = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the PlayerDecision message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum DecisionType {
        [pbr::OriginalName("NONE")] None = 0,
        [pbr::OriginalName("MOVE")] Move = 1,
        [pbr::OriginalName("ATTACK")] Attack = 2,
        [pbr::OriginalName("PORTAL")] Portal = 3,
        [pbr::OriginalName("DROP")] Drop = 4,
        [pbr::OriginalName("EQUIP")] Equip = 5,
        [pbr::OriginalName("PICKUP")] Pickup = 6,
      }

    }
    #endregion

  }

  /// <summary>
  /// Proto sent from engine to player
  /// </summary>
  public sealed partial class PlayerTurn : pb::IMessage<PlayerTurn>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerTurn> _parser = new pb::MessageParser<PlayerTurn>(() => new PlayerTurn());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PlayerTurn> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MM26.IO.Models.PlayerProtosReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerTurn() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerTurn(PlayerTurn other) : this() {
      gameState_ = other.gameState_ != null ? other.gameState_.Clone() : null;
      switch (other.TestCase) {
        case TestOneofCase.Test1:
          Test1 = other.Test1;
          break;
        case TestOneofCase.Test2:
          Test2 = other.Test2;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerTurn Clone() {
      return new PlayerTurn(this);
    }

    /// <summary>Field number for the "game_state" field.</summary>
    public const int GameStateFieldNumber = 1;
    private global::MM26.IO.Models.GameState gameState_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MM26.IO.Models.GameState GameState {
      get { return gameState_; }
      set {
        gameState_ = value;
      }
    }

    /// <summary>Field number for the "test1" field.</summary>
    public const int Test1FieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Test1 {
      get { return testCase_ == TestOneofCase.Test1 ? (string) test_ : ""; }
      set {
        test_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        testCase_ = TestOneofCase.Test1;
      }
    }

    /// <summary>Field number for the "test2" field.</summary>
    public const int Test2FieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Test2 {
      get { return testCase_ == TestOneofCase.Test2 ? (int) test_ : 0; }
      set {
        test_ = value;
        testCase_ = TestOneofCase.Test2;
      }
    }

    private object test_;
    /// <summary>Enum of possible cases for the "test" oneof.</summary>
    public enum TestOneofCase {
      None = 0,
      Test1 = 2,
      Test2 = 3,
    }
    private TestOneofCase testCase_ = TestOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TestOneofCase TestCase {
      get { return testCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearTest() {
      testCase_ = TestOneofCase.None;
      test_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PlayerTurn);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PlayerTurn other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(GameState, other.GameState)) return false;
      if (Test1 != other.Test1) return false;
      if (Test2 != other.Test2) return false;
      if (TestCase != other.TestCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (gameState_ != null) hash ^= GameState.GetHashCode();
      if (testCase_ == TestOneofCase.Test1) hash ^= Test1.GetHashCode();
      if (testCase_ == TestOneofCase.Test2) hash ^= Test2.GetHashCode();
      hash ^= (int) testCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (gameState_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(GameState);
      }
      if (testCase_ == TestOneofCase.Test1) {
        output.WriteRawTag(18);
        output.WriteString(Test1);
      }
      if (testCase_ == TestOneofCase.Test2) {
        output.WriteRawTag(24);
        output.WriteInt32(Test2);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (gameState_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GameState);
      }
      if (testCase_ == TestOneofCase.Test1) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Test1);
      }
      if (testCase_ == TestOneofCase.Test2) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Test2);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PlayerTurn other) {
      if (other == null) {
        return;
      }
      if (other.gameState_ != null) {
        if (gameState_ == null) {
          GameState = new global::MM26.IO.Models.GameState();
        }
        GameState.MergeFrom(other.GameState);
      }
      switch (other.TestCase) {
        case TestOneofCase.Test1:
          Test1 = other.Test1;
          break;
        case TestOneofCase.Test2:
          Test2 = other.Test2;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (gameState_ == null) {
              GameState = new global::MM26.IO.Models.GameState();
            }
            input.ReadMessage(GameState);
            break;
          }
          case 18: {
            Test1 = input.ReadString();
            break;
          }
          case 24: {
            Test2 = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (gameState_ == null) {
              GameState = new global::MM26.IO.Models.GameState();
            }
            input.ReadMessage(GameState);
            break;
          }
          case 18: {
            Test1 = input.ReadString();
            break;
          }
          case 24: {
            Test2 = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
