// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: visualizer.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MM26.IO.Models {

  /// <summary>Holder for reflection information generated from visualizer.proto</summary>
  public static partial class VisualizerReflection {

    #region Descriptor
    /// <summary>File descriptor for visualizer.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static VisualizerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChB2aXN1YWxpemVyLnByb3RvEhRwbGF5ZXJfY29tbXVuaWNhdGlvbhoPY2hh",
            "cmFjdGVyLnByb3RvIvIBChBWaXN1YWxpemVyQ2hhbmdlEhgKEG5ld19wbGF5",
            "ZXJfbmFtZXMYASADKAkSYAoWY2hhcmFjdGVyX3N0YXRfY2hhbmdlcxgCIAMo",
            "CzJALnBsYXllcl9jb21tdW5pY2F0aW9uLlZpc3VhbGl6ZXJDaGFuZ2UuQ2hh",
            "cmFjdGVyU3RhdENoYW5nZXNFbnRyeRpiChlDaGFyYWN0ZXJTdGF0Q2hhbmdl",
            "c0VudHJ5EgsKA2tleRgBIAEoCRI0CgV2YWx1ZRgCIAEoCzIlLnBsYXllcl9j",
            "b21tdW5pY2F0aW9uLkNoYXJhY3RlckNoYW5nZToCOAEihQEKD0NoYXJhY3Rl",
            "ckNoYW5nZRIMCgRkaWVkGAEgASgIEhEKCXJlc3Bhd25lZBgCIAEoCBIuCg1k",
            "ZWNpc2lvbl90eXBlGAMgASgOMhcuY2hhcmFjdGVyLkRlY2lzaW9uVHlwZRIh",
            "CgRwYXRoGAQgAygLMhMuY2hhcmFjdGVyLlBvc2l0aW9uQlwKN21lY2gubWFu",
            "aWEuZW5naW5lLnNlcnZlci5jb21tdW5pY2F0aW9uLnZpc3VhbGl6ZXIubW9k",
            "ZWxCEFZpc3VhbGl6ZXJQcm90b3OqAg5NTTI2LklPLk1vZGVsc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MM26.IO.Models.CharacterReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MM26.IO.Models.VisualizerChange), global::MM26.IO.Models.VisualizerChange.Parser, new[]{ "NewPlayerNames", "CharacterStatChanges" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::MM26.IO.Models.CharacterChange), global::MM26.IO.Models.CharacterChange.Parser, new[]{ "Died", "Respawned", "DecisionType", "Path" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class VisualizerChange : pb::IMessage<VisualizerChange>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<VisualizerChange> _parser = new pb::MessageParser<VisualizerChange>(() => new VisualizerChange());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<VisualizerChange> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MM26.IO.Models.VisualizerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VisualizerChange() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VisualizerChange(VisualizerChange other) : this() {
      newPlayerNames_ = other.newPlayerNames_.Clone();
      characterStatChanges_ = other.characterStatChanges_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VisualizerChange Clone() {
      return new VisualizerChange(this);
    }

    /// <summary>Field number for the "new_player_names" field.</summary>
    public const int NewPlayerNamesFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_newPlayerNames_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> newPlayerNames_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> NewPlayerNames {
      get { return newPlayerNames_; }
    }

    /// <summary>Field number for the "character_stat_changes" field.</summary>
    public const int CharacterStatChangesFieldNumber = 2;
    private static readonly pbc::MapField<string, global::MM26.IO.Models.CharacterChange>.Codec _map_characterStatChanges_codec
        = new pbc::MapField<string, global::MM26.IO.Models.CharacterChange>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::MM26.IO.Models.CharacterChange.Parser), 18);
    private readonly pbc::MapField<string, global::MM26.IO.Models.CharacterChange> characterStatChanges_ = new pbc::MapField<string, global::MM26.IO.Models.CharacterChange>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::MM26.IO.Models.CharacterChange> CharacterStatChanges {
      get { return characterStatChanges_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as VisualizerChange);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(VisualizerChange other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!newPlayerNames_.Equals(other.newPlayerNames_)) return false;
      if (!CharacterStatChanges.Equals(other.CharacterStatChanges)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= newPlayerNames_.GetHashCode();
      hash ^= CharacterStatChanges.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      newPlayerNames_.WriteTo(output, _repeated_newPlayerNames_codec);
      characterStatChanges_.WriteTo(output, _map_characterStatChanges_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += newPlayerNames_.CalculateSize(_repeated_newPlayerNames_codec);
      size += characterStatChanges_.CalculateSize(_map_characterStatChanges_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(VisualizerChange other) {
      if (other == null) {
        return;
      }
      newPlayerNames_.Add(other.newPlayerNames_);
      characterStatChanges_.Add(other.characterStatChanges_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            newPlayerNames_.AddEntriesFrom(input, _repeated_newPlayerNames_codec);
            break;
          }
          case 18: {
            characterStatChanges_.AddEntriesFrom(input, _map_characterStatChanges_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            newPlayerNames_.AddEntriesFrom(ref input, _repeated_newPlayerNames_codec);
            break;
          }
          case 18: {
            characterStatChanges_.AddEntriesFrom(ref input, _map_characterStatChanges_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CharacterChange : pb::IMessage<CharacterChange>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CharacterChange> _parser = new pb::MessageParser<CharacterChange>(() => new CharacterChange());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CharacterChange> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MM26.IO.Models.VisualizerReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CharacterChange() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CharacterChange(CharacterChange other) : this() {
      died_ = other.died_;
      respawned_ = other.respawned_;
      decisionType_ = other.decisionType_;
      path_ = other.path_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CharacterChange Clone() {
      return new CharacterChange(this);
    }

    /// <summary>Field number for the "died" field.</summary>
    public const int DiedFieldNumber = 1;
    private bool died_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Died {
      get { return died_; }
      set {
        died_ = value;
      }
    }

    /// <summary>Field number for the "respawned" field.</summary>
    public const int RespawnedFieldNumber = 2;
    private bool respawned_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Respawned {
      get { return respawned_; }
      set {
        respawned_ = value;
      }
    }

    /// <summary>Field number for the "decision_type" field.</summary>
    public const int DecisionTypeFieldNumber = 3;
    private global::MM26.IO.Models.DecisionType decisionType_ = global::MM26.IO.Models.DecisionType.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MM26.IO.Models.DecisionType DecisionType {
      get { return decisionType_; }
      set {
        decisionType_ = value;
      }
    }

    /// <summary>Field number for the "path" field.</summary>
    public const int PathFieldNumber = 4;
    private static readonly pb::FieldCodec<global::MM26.IO.Models.Position> _repeated_path_codec
        = pb::FieldCodec.ForMessage(34, global::MM26.IO.Models.Position.Parser);
    private readonly pbc::RepeatedField<global::MM26.IO.Models.Position> path_ = new pbc::RepeatedField<global::MM26.IO.Models.Position>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::MM26.IO.Models.Position> Path {
      get { return path_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CharacterChange);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CharacterChange other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Died != other.Died) return false;
      if (Respawned != other.Respawned) return false;
      if (DecisionType != other.DecisionType) return false;
      if(!path_.Equals(other.path_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Died != false) hash ^= Died.GetHashCode();
      if (Respawned != false) hash ^= Respawned.GetHashCode();
      if (DecisionType != global::MM26.IO.Models.DecisionType.None) hash ^= DecisionType.GetHashCode();
      hash ^= path_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Died != false) {
        output.WriteRawTag(8);
        output.WriteBool(Died);
      }
      if (Respawned != false) {
        output.WriteRawTag(16);
        output.WriteBool(Respawned);
      }
      if (DecisionType != global::MM26.IO.Models.DecisionType.None) {
        output.WriteRawTag(24);
        output.WriteEnum((int) DecisionType);
      }
      path_.WriteTo(output, _repeated_path_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Died != false) {
        size += 1 + 1;
      }
      if (Respawned != false) {
        size += 1 + 1;
      }
      if (DecisionType != global::MM26.IO.Models.DecisionType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) DecisionType);
      }
      size += path_.CalculateSize(_repeated_path_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CharacterChange other) {
      if (other == null) {
        return;
      }
      if (other.Died != false) {
        Died = other.Died;
      }
      if (other.Respawned != false) {
        Respawned = other.Respawned;
      }
      if (other.DecisionType != global::MM26.IO.Models.DecisionType.None) {
        DecisionType = other.DecisionType;
      }
      path_.Add(other.path_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Died = input.ReadBool();
            break;
          }
          case 16: {
            Respawned = input.ReadBool();
            break;
          }
          case 24: {
            DecisionType = (global::MM26.IO.Models.DecisionType) input.ReadEnum();
            break;
          }
          case 34: {
            path_.AddEntriesFrom(input, _repeated_path_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Died = input.ReadBool();
            break;
          }
          case 16: {
            Respawned = input.ReadBool();
            break;
          }
          case 24: {
            DecisionType = (global::MM26.IO.Models.DecisionType) input.ReadEnum();
            break;
          }
          case 34: {
            path_.AddEntriesFrom(ref input, _repeated_path_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
